package io.simpleit.umbrella.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExpenseTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseTypeAllPropertiesEquals(ExpenseType expected, ExpenseType actual) {
        assertExpenseTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertExpenseTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseTypeAllUpdatablePropertiesEquals(ExpenseType expected, ExpenseType actual) {
        assertExpenseTypeUpdatableFieldsEquals(expected, actual);
        assertExpenseTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseTypeAutoGeneratedPropertiesEquals(ExpenseType expected, ExpenseType actual) {
        assertThat(expected)
            .as("Verify ExpenseType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseTypeUpdatableFieldsEquals(ExpenseType expected, ExpenseType actual) {
        assertThat(expected)
            .as("Verify ExpenseType relevant properties")
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getReimbursmentPct()).as("check reimbursmentPct").isEqualTo(actual.getReimbursmentPct()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseTypeUpdatableRelationshipsEquals(ExpenseType expected, ExpenseType actual) {}
}
