package io.simpleit.umbrella.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FormulaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormulaAllPropertiesEquals(Formula expected, Formula actual) {
        assertFormulaAutoGeneratedPropertiesEquals(expected, actual);
        assertFormulaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormulaAllUpdatablePropertiesEquals(Formula expected, Formula actual) {
        assertFormulaUpdatableFieldsEquals(expected, actual);
        assertFormulaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormulaAutoGeneratedPropertiesEquals(Formula expected, Formula actual) {
        assertThat(expected)
            .as("Verify Formula auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormulaUpdatableFieldsEquals(Formula expected, Formula actual) {
        assertThat(expected)
            .as("Verify Formula relevant properties")
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getAdminFeesPct()).as("check adminFeesPct").isEqualTo(actual.getAdminFeesPct()))
            .satisfies(e -> assertThat(e.getAdditionalFeesPct()).as("check additionalFeesPct").isEqualTo(actual.getAdditionalFeesPct()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormulaUpdatableRelationshipsEquals(Formula expected, Formula actual) {}
}
