package io.simpleit.umbrella.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParameterGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParameterGroupAllPropertiesEquals(ParameterGroup expected, ParameterGroup actual) {
        assertParameterGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertParameterGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParameterGroupAllUpdatablePropertiesEquals(ParameterGroup expected, ParameterGroup actual) {
        assertParameterGroupUpdatableFieldsEquals(expected, actual);
        assertParameterGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParameterGroupAutoGeneratedPropertiesEquals(ParameterGroup expected, ParameterGroup actual) {
        assertThat(expected)
            .as("Verify ParameterGroup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParameterGroupUpdatableFieldsEquals(ParameterGroup expected, ParameterGroup actual) {
        assertThat(expected)
            .as("Verify ParameterGroup relevant properties")
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParameterGroupUpdatableRelationshipsEquals(ParameterGroup expected, ParameterGroup actual) {}
}
