package io.simpleit.umbrella.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimeSheetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSheetAllPropertiesEquals(TimeSheet expected, TimeSheet actual) {
        assertTimeSheetAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeSheetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSheetAllUpdatablePropertiesEquals(TimeSheet expected, TimeSheet actual) {
        assertTimeSheetUpdatableFieldsEquals(expected, actual);
        assertTimeSheetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSheetAutoGeneratedPropertiesEquals(TimeSheet expected, TimeSheet actual) {
        assertThat(expected)
            .as("Verify TimeSheet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSheetUpdatableFieldsEquals(TimeSheet expected, TimeSheet actual) {
        assertThat(expected)
            .as("Verify TimeSheet relevant properties")
            .satisfies(e -> assertThat(e.getConcernedMonth()).as("check concernedMonth").isEqualTo(actual.getConcernedMonth()))
            .satisfies(e -> assertThat(e.getCreationDate()).as("check creationDate").isEqualTo(actual.getCreationDate()))
            .satisfies(e -> assertThat(e.getSubmitDate()).as("check submitDate").isEqualTo(actual.getSubmitDate()))
            .satisfies(e -> assertThat(e.getValidationDate()).as("check validationDate").isEqualTo(actual.getValidationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSheetUpdatableRelationshipsEquals(TimeSheet expected, TimeSheet actual) {
        assertThat(expected)
            .as("Verify TimeSheet relationships")
            .satisfies(e -> assertThat(e.getProject()).as("check project").isEqualTo(actual.getProject()))
            .satisfies(e -> assertThat(e.getDocument()).as("check document").isEqualTo(actual.getDocument()))
            .satisfies(e -> assertThat(e.getEmployee()).as("check employee").isEqualTo(actual.getEmployee()));
    }
}
